name: SonarCloud
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.sast }}
        with:
          args: >
            -Dsonar.projectKey=PerezMigue1_Miru-Franco
            -Dsonar.organization=idashido
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

